#!/bin/bash
set -xeuo pipefail

mkdir -p /var/lib/kudu/master
mkdir -p /var/lib/kudu/tserver

ulimit -u 20000

KUDU_MASTER=localhost
KUDU_MASTER_OPTS="--logtostderr \
         --fs_wal_dir=/var/lib/kudu/master \
         --fs_data_dirs=/var/lib/kudu/master \
         --webserver_doc_root=/opt/kudu/www \
         --use_hybrid_clock=false"
KUDU_TSERVER_OPTS="--logtostderr \
         --fs_wal_dir=/var/lib/kudu/tserver \
         --fs_data_dirs=/var/lib/kudu/tserver \
         --webserver_doc_root=/opt/kudu/www \
         --use_hybrid_clock=false"

/opt/kudu/kudu-master -fs_wal_dir /var/lib/kudu/master ${KUDU_MASTER_OPTS} &
sleep 5s
/opt/kudu/kudu-tserver -fs_wal_dir /var/lib/kudu/tserver \
        -tserver_master_addrs ${KUDU_MASTER} ${KUDU_TSERVER_OPTS}
